# docker build -t apimagic:1.0 .
# docker run -p 8080:8080 -t apimagic:1.0
# flyctl deploy --local-only --image apimagic:1.0

app = "apimagic"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/apimagic:latest"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
